<h3>This new page is generated by CRM/Civiquickbooks/Page/DevTest.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>

<pre>Test Result 1: {$test_var1}</pre>



<pre>Test Result 2: {$test_var2}</pre>



<pre>Test Result 3: {$test_var3}</pre>




<pre>Test Result 4: {$test_var4}</pre>