name: Cut release

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version to release (must match <version> in info.xml)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  cut-release:
    uses: agileware/ci-workflows/.github/workflows/civicrm-extension-cut-release.yml@main
    with:
      VERSION: ${{ inputs.VERSION }}
      EXCLUDE_PATHS: ".github composer.lock tests .idea .gitignore CONTRIBUTING.md DEVELOPERS.md"
